name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v12.18.3
        uses: actions/setup-node@v1
        with:
            node-version: "12.18.3"

      - name: Build Docs
        working-directory: ./docs
        run: |
          yarn install -D
          yarn build

      - name: Copy Build files
        run: cp -r ./docs/src/.vuepress/dist ./build-docs

      - name: Delete existing Docs
        run: rm -rf ./docs

      - name: Rename Build to Docs
        run: mv ./build-docs ./docs

      - name: CNAME & NoJekyll
        run: |
          echo 'keydb.zyrouge.gq' > ./build-docs/CNAME
          touch .nojekyll

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
