name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v12.18.3
        uses: actions/setup-node@v1
        with:
            node-version: "12.18.3"

      - name: Build Docs
        working-directory: ./docs
        run: |
          yarn install -D
          yarn build

      - run: ls

      - name: Init and Add files
        working-directory: ./docs/src/.vuepress/dist
        run: |
            git init
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
            git checkout gh-pages
            git add .

      - name: Commit and Push files
        working-directory: ./docs/src/.vuepress/dist
        run: |
            git remote -v
            git commit -m "Added build files"
            git push origin gh-pages -f
