name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS v12.18.3
        uses: actions/setup-node@v1
        with:
            node-version: "12.18.3"

      - name: Goto Docs
        run: cd docs

      - name: Install packages
        run: yarn install -D

      - name: Build
        run: yarn build

      - name: Goto Dist
        run: cd src/.vuepress/dist

      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit . -m "Added build files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            force: true
